M48
; DRILL file {KiCad 9.0.0} date 2025-03-15T22:01:38-0400
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-03-15T22:01:38-04:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,9.0.0
; #@! TF.FileFunction,NonPlated,1,6,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X219.059Y-84.995
X224.839Y-84.995
T2
X119.0Y-102.0
X119.0Y-202.0
X238.0Y-102.0
X238.0Y-202.0
M30
