M48
; DRILL file {KiCad 8.0.7} date 2025-01-15T12:36:31-0500
; FORMAT={-:-/ absolute / metric / decimal}
; #@! TF.CreationDate,2025-01-15T12:36:31-05:00
; #@! TF.GenerationSoftware,Kicad,Pcbnew,8.0.7
; #@! TF.FileFunction,NonPlated,1,4,NPTH
FMAT,2
METRIC
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T1C0.650
; #@! TA.AperFunction,NonPlated,NPTH,ComponentDrill
T2C3.500
%
G90
G05
T1
X212.09Y-84.945
X217.87Y-84.945
T2
X119.0Y-106.0
X119.0Y-202.0
X238.0Y-106.0
X238.0Y-202.0
M30
